name: demo_innt
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^1.1.2
  flutter_verification_code: ^1.1.7
  intl: any
  country_calling_code_picker: ^2.0.1
  qr_code_scanner: ^1.0.1
  camera: ^0.10.5+6
  flutter_lints: ^2.0.0
  get: ^4.6.6
  google_fonts: ^6.1.0
  image_picker: ^1.0.5
  intl_phone_field: ^3.2.0
  dotted_border: ^2.1.0
  date_format: ^2.0.7
  google_maps_flutter: ^2.5.0
  persistent_bottom_nav_bar: ^5.0.2
  provider: ^6.1.1
  url_launcher: ^6.1.11
  flutter_polyline_points: ^2.0.0
  geocoding: ^2.1.0
  geolocator: ^10.1.0
  fluttertoast: ^8.2.4
  pinput: ^3.0.1
  shared_preferences: ^2.2.2
  flutter_switch: ^0.3.2
  introduction_screen: ^3.1.12
  syncfusion_flutter_charts: ^24.1.45
  chat_bubbles: ^1.5.0
  multi_image_picker_view: ^1.0.0
  multiple_images_picker: ^1.0.1
  multi_dropdown: ^2.1.4
  multiselect: ^0.1.0
  country_code_picker: ^3.0.0
  flutter_city_picker: ^2.1.1
  flutter_rating_bar: ^4.0.1
  google_places_flutter_api: ^1.0.2
  google_places_for_flutter_plus: ^2.0.1
  google_places_autocomplete_flutter: ^1.0.6
  qr: ^3.0.1
  qr_flutter: ^4.1.0
  permission_handler: any
  open_file: ^3.2.1
  video_player: any
  custom_refresh_indicator: ^3.1.0
  file_picker: any
  audioplayers: any
  flutter_chat_bubble: any
  vengamo_chat_ui: ^1.4.8
  permission_handler_web: ^0.0.2
  flutter_html: ^3.0.0-beta.2
  pretty_qr_code: ^3.3.0
  screenshot: any
  path_provider: ^2.1.3
  share_plus: any
  external_path: ^1.0.3
  change_app_package_name: ^1.1.0
  firebase_core: any
  firebase_auth: any
  firebase_messaging: any
  firebase_database: any
  firebase_storage: any
  firebaseapis: any
  cloud_firestore: any
  flutter_local_notifications: ^16.1.0



#dependency_overrides:
#  screenshot: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_localizations:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec



# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  fonts:
    - family: Regular
      fonts:
        - asset: Font_Family/amazon-ember-cufonfonts/DrSugiyama-Regular.ttf

    - family: Ember
      fonts:
        - asset: Font_Family/amazon-ember-cufonfonts/Amazon Ember.ttf

    - family: Ember_Bold
      fonts:
          - asset: Font_Family/amazon-ember-cufonfonts/Amazon Ember Bold.ttf

    - family: Ember_Display_Medium
      fonts:
        - asset: Font_Family/amazon-ember-cufonfonts/Amazon Ember Display Medium.ttf

    - family: Ember_Thin
      fonts:
        - asset: Font_Family/amazon-ember-cufonfonts/Amazon Ember Cd RC Thin.ttf

    - family: Ember_Light
      fonts:
        - asset: Font_Family/amazon-ember-cufonfonts/Amazon Ember Display Light.ttf
   

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
