// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF_pIUNxQv9UXmv0e7RC5Uiy3_jr_ML8U',
    appId: '1:321243157659:web:f2f15a22e387a7f48f223e',
    messagingSenderId: '321243157659',
    projectId: 'innt-6700e',
    authDomain: 'innt-6700e.firebaseapp.com',
    databaseURL: 'https://innt-6700e-default-rtdb.firebaseio.com',
    storageBucket: 'innt-6700e.appspot.com',
    measurementId: 'G-PT9GXWWY6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArsQnDJ5T01r1Q_UkvGJ-HWXOhHaW2Zrk',
    appId: '1:321243157659:android:7d38763700c0271a8f223e',
    messagingSenderId: '321243157659',
    projectId: 'innt-6700e',
    databaseURL: 'https://innt-6700e-default-rtdb.firebaseio.com',
    storageBucket: 'innt-6700e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuu5vEslipom0a3wlf8vUW8Hh1Vm2Hio8',
    appId: '1:321243157659:ios:c6e27eb258a46a3f8f223e',
    messagingSenderId: '321243157659',
    projectId: 'innt-6700e',
    databaseURL: 'https://innt-6700e-default-rtdb.firebaseio.com',
    storageBucket: 'innt-6700e.appspot.com',
    iosBundleId: 'com.example.demoInnt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuu5vEslipom0a3wlf8vUW8Hh1Vm2Hio8',
    appId: '1:321243157659:ios:c6e27eb258a46a3f8f223e',
    messagingSenderId: '321243157659',
    projectId: 'innt-6700e',
    databaseURL: 'https://innt-6700e-default-rtdb.firebaseio.com',
    storageBucket: 'innt-6700e.appspot.com',
    iosBundleId: 'com.example.demoInnt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF_pIUNxQv9UXmv0e7RC5Uiy3_jr_ML8U',
    appId: '1:321243157659:web:b7264b5311e73b258f223e',
    messagingSenderId: '321243157659',
    projectId: 'innt-6700e',
    authDomain: 'innt-6700e.firebaseapp.com',
    databaseURL: 'https://innt-6700e-default-rtdb.firebaseio.com',
    storageBucket: 'innt-6700e.appspot.com',
    measurementId: 'G-ZWED91PM0K',
  );
}
